import pandas as pd
import os

def process_finance_data():
    print("Starting Finance 4.0 Data Pipeline...")
    
    # 1. Ensure the output directory exists
    os.makedirs('data/processed', exist_ok=True)
    
    # 2. Load the raw data generated by your mock script
    try:
        raw_df = pd.read_csv('data/raw/raw_ops_data.csv')
    except FileNotFoundError:
        print("Error: raw_ops_data.csv not found. Run generate_mock_data.py first.")
        return

    # 3. Calculate Core Financial Metrics (The "Finance Logic")
    # CM2 = Revenue - COGS - Logistics - Waste
    raw_df['CM2_Net_Cash'] = (
        raw_df['Revenue'] - 
        raw_df['COGS'] - 
        raw_df['Logistics_Cost'] - 
        raw_df['Waste_Loss']
    )
    
    # 4. Create the 'daily_cash_forecast.csv' needed by app.py
    # We select only the columns the dashboard needs to avoid memory bloat
    forecast_df = raw_df[[
        'Date', 
        'Hub_Location', 
        'Revenue', 
        'CM2_Net_Cash', 
        'Waste_Loss'
    ]].copy()
    
    # 5. Save the output
    # This matches the filename we see in your GitHub 'data/processed' folder
    output_path = 'data/processed/daily_cash_forecast.csv'
    forecast_df.to_csv(output_path, index=False)
    
    print(f"Success! Processed data saved to: {output_path}")
    print(f"Columns exported: {forecast_df.columns.tolist()}")

if __name__ == "__main__":
    process_finance_data()